all:
  children:
    _app:
      hosts:
        62.84.113.95:
          ansible_host: 62.84.113.13
    _db:
      hosts:
        130.193.38.65:
          ansible_host: 130.193.38.156
    ungrouped: {}
